### ISSUE TITLE
Exception: TypeError: the JSON object must be str, not 'bytes' 

### ISSUE THREAD

**Issue by thuyminhtran** [fossology/fossdriver#14]
Hello,

I tried to install fossdriver (master branch: b950917).
My environment:
- Ubuntu: 16.04
- Python: 3.5

I get this error below

> Exception: TypeError: the JSON object must be str, not 'bytes' 

In  parser.py (func: parseSingleJobData) and server.py (func: decodeAjaxShowJobsData),

I have added ".decode('utf-8')" to fix this error.
E.g.
from
> rj = json.loads(content)

to
> rj = json.loads(content.decode('utf-8'))

Can you check it?

Best regards,
Thuy

**Comment by leimaohui** [comment]
I created a pull request to fix the issue.

**Comment by swinslow** [comment]
I believe this was fixed by #16 submitted by @leimaohui, so I'm going to go ahead and close this issue. Please feel free to re-open if you're still seeing the problem here. Thanks!
