### ISSUE TITLE
Can't work with latest fossology

### ISSUE THREAD

**Issue by leimaohui** [fossology/fossdriver#17]
fossdriver can't with the fossology after 3.5.0. The following error will be output:
......
   Upload(server, "xz-5.2.1.tar.gz", "Software Repository").run()
/fossdriver/fossdriver/tasks.py", line 73, in run
    self.server.WaitUntilAgentIsDone(newUploadNum, "ununpack", pollSeconds=5)
/fossdriver/fossdriver/server.py", line 
410, in WaitUntilAgentIsDone
    jobNum = self._getMostRecentAgentJobNum(uploadNum, agent)
/fossdriver/fossdriver/server.py", line 
250, in _getMostRecentAgentJobNum
    jobs = self._getJobsForUpload(uploadNum)
/fossdriver/fossdriver/server.py", line 
237, in _getJobsForUpload
    decodedContent = fossdriver.parser.decodeAjaxShowJobsData(results.content)
/fossdriver/fossdriver/parser.py", line 
147, in decodeAjaxShowJobsData
    b1 = s1.encode("utf-8")
AttributeError: 'list' object has no attribute 'encode'

It is because the data from fossology changes from xml to json format. So, there are many functions to update.

**Comment by deveaud-m** [comment]
I could also verify this issue. The changes in FOSSology have been introduced by this PR: https://github.com/fossology/fossology/pull/1338.

The helper function `_getMostRecentAgentJobNum()` should be rewritten to differentiate show jobs data from different FOSSology server versions.

**Comment by swinslow** [comment]
Hi @leimaohui and @deveaud-m, thanks for flagging and verifying this issue. 

I don't yet have a 3.5.0 server installed, so if you have a PR to fix this, feel free to submit and I'll gladly merge it in! Otherwise, I'll review after I upgrade the server I'm currently using (which is still on 3.3.0). Thank you!

**Comment by leimaohui** [comment]
I'm sorry I don't have patch. If I have time to fix it, I will submit my patch.

**Comment by swinslow** [comment]
Hi @leimaohui, as a heads-up I've now updated my own Fossology server installation to version 3.6.0. So I will be working on updating fossdriver to handle the issue you reported.

**Comment by swinslow** [comment]
@leimaohui and @deveaud-m, I'd welcome any input on the PR at #21, particularly if that fixes the problem you're seeing here. Thanks!
