### ISSUE TITLE
Should be modified to work with versions of Python prior to 3.6

### ISSUE THREAD

**Issue by swinslow** [fossology/fossdriver#3]
Replacing f-strings with .format() should (hopefully) enable fossdriver to work with versions of Python older than 3.6.

Additionally, some users may still be using Python 2. It would be ideal if fossdriver were modified to the extent needed to work with Python 2.

**Comment by max-wittig** [comment]
Python2 is legacy python. It will reach it's end of life in less than 1,5 years. Every operating system supports using newer python versions. 

For supporting older 3.X versions, I would recommend to rather use something like https://github.com/nvbn/py-backwards

**Comment by swinslow** [comment]
Thanks @max-wittig. I agree, I don't use Python 2, but I've had a request for support from at least one person interested in fossdriver who is stuck using Python 2 for now.
